import math 

class Config:
    def __init__(self):
        self.verbose = True
        self.network = "custom"

        self.use_horizontal_flips = False
        self.use_vertical_flips = False
        self.balanced_classes = False

        self.rot_90 = False

        # Orig Anchor Box [128, 256, 512]
        self.anchor_box_scales = [32, 64, 128]

        self.anchor_box_ratios = [[1, 1], [1./math.sqrt(2), 2./math.sqrt(2)], [2./math.sqrt(2), 1./math.sqrt(2)]]
        
        self.im_size = 200

        self.num_rois = 4

        self.rpn_stride = 16

        # scaling the stdev
        self.std_scaling = 4.0
        self.classifier_regr_std = [8.0, 8.0, 4.0, 4.0]

        # overlaps for RPN
        self.rpn_min_overlap = 0.3
        self.rpn_max_overlap = 0.7

        # overlaps for classifier ROIs
        self.classifier_min_overlap = 0.1
        self.classifier_max_overlap = 0.5

        # placeholder for the class mapping, automatically generated by the parser
        self.class_mapping = None

        self.model_path = None

        

